admin_email: admin@domain.org
admin_name: Admin Name
config_status: true
homepage: homepage@domain.org
provider: My Organization
ranames: C:\Users\mpastor\soft\NAMASTOX\ranames
root_repository: C:\Users\mpastor\soft\NAMASTOX
