name: namastox
channels:
  - default
  - rdkit
  - conda-forge 
  - chembl
dependencies:
  - python=3.10
  - numpy=1.26.*
  - scikit-learn=1.4.*
  - rdkit=2023.09.*
  - imbalanced-learn=0.12.*
  - pip
  - setuptools
  - chembl_structure_pipeline
  - requests
  - flask
  - flask_cors
  - python-dotenv
  - pyjwt
  - pyyaml
  - pytest
  - psycopg2
  - python-docx
  - XlsxWriter
  - appdirs
  - pip:
     - xgboost
     - "https://github.com/phi-grib/standardiser/archive/master.zip"
     - "https://github.com/phi-grib/nonconformist/archive/master.zip"
     