name: namastox
channels:
  - default
  - rdkit
  - conda-forge 
dependencies:
  - pip
  - python=3.10
  - numpy
  - setuptools
  - requests
  - rdkit
  - flask
  - pyyaml
  - pytest
  - psycopg2
  - python-docx
  - openpyxl
  - appdirs
