name: namastox2
channels:
  - default
  - rdkit
  - conda-forge 
  - chembl
dependencies:
  - pip
  - python=3.10
  - numpy
  - setuptools
  - scikit-learn
  - imbalanced-learn
  - chembl_structure_pipeline
  - rdkit
  - requests
  - flask
  - flask_cors
  - pyyaml
  - pytest
  - psycopg2
  - python-docx
  - openpyxl
  - appdirs
  - pip:
     - xgboost
     - python-keycloak
     - "https://github.com/phi-grib/standardiser/archive/master.zip"
     - "https://github.com/phi-grib/nonconformist/archive/master.zip"
     